== Empty Repository

This is just an empty repository to play around with some Diagrams-as-Code tools.

To open this repository in gitpod, just preface the URL with `gitpod.io#`.

Next, gitpod will start a web based visual studio instance with everything pre-installed.

Open this `README.adoc` and press `Ctrl+k` then `v` to aktivate the AsciiDoc preview.

Now open xref:src/docs/diagrams-as-code.adoc[] and start hacking.

'''

=== advanced

To install _docToolchain_, switch to the terminal and run

[code, bash]
----
curl -Lo dtcw doctoolchain.github.io/dtcw
chmod +x dtcw
./dtcw install doctoolchain
----

To preview the files, start a small server from within the terminal:

[code, bash]
----
python -m http.server 8000
----

Gitpod will now ask you what to do with the opened port. Just click on "open in browser" and navigate through the `build` folder.

=== Structurizr

run structurizr lite as docker container

    docker run -it --rm -p 8080:8080 -v $(pwd)/workspaces:/usr/local/structurizr structurizr/lite

get the CLI to export images

    wget https://github.com/structurizr/cli/releases/download/2024.01.02/structurizr-cli.zip
    unzip structurizr-cli.zip

    